wget "https://towardsdatascience.com/a-quick-introduction-to-text-summarization-in-machine-learning-3d27ccf18a9f" -O ./files/0_positive
wget "https://medium.com/luisfredgs/automatic-text-summarization-with-machine-learning-an-overview-68ded5717a25" -O ./files/1
wget "https://www.machinelearningplus.com/nlp/text-summarization-approaches-nlp-example/" -O ./files/2
wget "https://www.analyticsvidhya.com/blog/2019/06/comprehensive-guide-text-summarization-using-deep-learning-python/" -O ./files/3
wget "https://paperswithcode.com/task/text-summarization" -O ./files/4
wget "https://machinelearningmastery.com/gentle-introduction-text-summarization/" -O ./files/5
wget "https://analyticsindiamag.com/hands-on-guide-to-extractive-text-summarization-with-bertsum/" -O ./files/6
wget "https://link.springer.com/10.1007/978-0-387-39940-9_424" -O ./files/7
wget "https://www.coverwallet.com/expert-insights/nlp-text-summarization-for-businesses" -O ./files/8
wget "https://www.kdnuggets.com/2019/01/approaches-text-summarization-overview.html" -O ./files/9
wget "https://www.kdnuggets.com/2019/12/automatic-text-summarization-nutshell.html" -O ./files/10_positive
wget "https://blog.floydhub.com/gentle-introduction-to-text-summarization-in-machine-learning/" -O ./files/11_positive
wget "https://www.quora.com/What-are-the-real-world-applications-of-automatic-text-summarization" -O ./files/12_positive
wget "https://arxiv.org/pdf/2107.14691.pdf" -O ./files/13_positive
