wget "https://en.wikipedia.org/wiki/Document-term_matrix" -O ./files/0_positive
wget "https://www.darrinbishop.com/blog/2017/10/text-analytics-document-term-matrix/" -O ./files/1_positive
wget "https://datawarrior.wordpress.com/2018/01/22/document-term-matrix-text-mining-in-r-and-python/" -O ./files/2_positive
wget "https://www.tidytextmining.com/dtm.html" -O ./files/3_positive
wget "https://gerardnico.com/natural_language/term_document" -O ./files/4_positive
wget "https://www.displayr.com/text-analysis-hooking-up-your-term-document-matrix-to-custom-r-code/" -O ./files/5_positive
wget "https://datascience.blog.wzb.eu/2016/06/17/creating-a-sparse-document-term-matrix-for-topic-modeling-via-lda/" -O ./files/6_positive
wget "https://www.r-bloggers.com/text-analysis-hooking-up-your-term-document-matrix-to-custom-r-code/" -O ./files/7_positive
wget "https://ml-withparag.com/f/nlp-blog-5-creating-document-term-matrix-dtm" -O ./files/8
wget "https://wiki.q-researchsoftware.com/wiki/Text_Analysis_-_Advanced_-_Create_Term_Document_Matrix" -O ./files/9_positive
wget "https://rpubs.com/tvganesh/textmining" -O ./files/10_positive
wget "http://rstudio-pubs-static.s3.amazonaws.com/188848_27efa9e6c1934d869e9ca6bcf19d83f7.html" -O ./files/11_positive
wget "https://rstudio-pubs-static.s3.amazonaws.com/132792_864e3813b0ec47cb95c7e1e2e2ad83e7.html" -O ./files/12_positive
wget "https://srdas.github.io/MLBook/TextAnalytics.html#term-document-matrix-tdm" -O ./files/13
wget "http://downloads.hindawi.com/journals/sp/2019/1095643.pdf" -O ./files/14
wget "https://arxiv.org/pdf/1708.06068.pdf" -O ./files/15
wget "https://analytics4all.org/tag/term-document-matrix/" -O ./files/16
wget "http://www.socr.umich.edu/people/dinov/courses/DSPA_notes/19_NLP_TextMining.html" -O ./files/17
wget "https://towardsdatascience.com/create-a-word-cloud-with-r-bde3e7422e8a" -O ./files/18
wget "https://shorttext.readthedocs.io/en/latest/tutorial_dtm.html" -O ./files/19
